export const skills = [
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "Teamwork",
  "CSS BEM convention",
  "CSS Flexbox, Grid",
  "React Router",
  "Redux-Saga",
  "Redux (Toolkit)",
  "React Hooks",
  "Working with API (fetch, axios)",
  "JavaScript ES6+",
  "Promises, Async/Await",
  "GitHub Pull Requests & Review",
  "Trello",
  "Scrum",
  "NPM",
];

export const nextSkills = [
  "React Context",
  "Cypress",
  "TypeScript",
  "Node.js",
  "Unit testing",
  "JS classes",
  "Tanstack Query",
  "SolidJS",
  "Vue",
  "Jest, RTL",
  "Vite Tool",
];
